-- Script SQL pour corriger la table pv_price_bands

-- 1. Vérifier si la table existe et la créer si nécessaire
CREATE TABLE IF NOT EXISTS public.pv_price_bands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_key TEXT NOT NULL,
  label TEXT NOT NULL,
  min NUMERIC,
  max NUMERIC,
  share_pct NUMERIC DEFAULT 0,
  sort INTEGER DEFAULT 0,
  bike_category TEXT,
  bike_type TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Ajouter les colonnes manquantes si elles n'existent pas
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'pv_price_bands' AND column_name = 'bike_category'
  ) THEN
    ALTER TABLE public.pv_price_bands ADD COLUMN bike_category TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'pv_price_bands' AND column_name = 'bike_type'
  ) THEN
    ALTER TABLE public.pv_price_bands ADD COLUMN bike_type TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'pv_price_bands' AND column_name = 'sort'
  ) THEN
    ALTER TABLE public.pv_price_bands ADD COLUMN sort INTEGER DEFAULT 0;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'pv_price_bands' AND column_name = 'created_at'
  ) THEN
    ALTER TABLE public.pv_price_bands ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'pv_price_bands' AND column_name = 'updated_at'
  ) THEN
    ALTER TABLE public.pv_price_bands ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
  END IF;
END $$;

-- 3. Créer un index unique pour éviter les doublons par (bike_category, bike_type, category_key)
DROP INDEX IF EXISTS pv_price_bands_unique_idx;
CREATE UNIQUE INDEX pv_price_bands_unique_idx 
ON public.pv_price_bands (bike_category, bike_type, category_key);

-- 4. Activer Row Level Security (RLS) si vous l'utilisez
ALTER TABLE public.pv_price_bands ENABLE ROW LEVEL SECURITY;

-- 5. Créer une politique pour permettre toutes les opérations (à ajuster selon vos besoins)
DROP POLICY IF EXISTS "Enable all operations for authenticated users" ON public.pv_price_bands;
CREATE POLICY "Enable all operations for authenticated users" 
ON public.pv_price_bands 
FOR ALL 
USING (true) 
WITH CHECK (true);

-- 6. Vérifier les données existantes
SELECT id, category_key, label, min, max, share_pct, bike_category, bike_type 
FROM public.pv_price_bands 
ORDER BY bike_category, bike_type, id;
